# This is a basic workflow to help you get started with Actions
# See for reference:
# https://github.com/scikit-image/scikit-image/blob/main/.github/workflows/benchmarks.yml#L77

###############################
# Metadata for this workflow
###############################
name: benchmarks

###############################
# Triggers
###############################
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
#   schedule:
    # set this to whatever is reasonable for the specific project
    # * is a special character in YAML so you have to quote this string
    # - cron:  '0 * * * *' # hourly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


###############################
# Permissions
###############################
# permissions:
#     contents: read
      

###############################
# Jobs
###############################
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "benchmark"
  benchmark:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Create virtual environment?
      - name: Create virtual environment
        run: echo "$GITHUB_WORKSPACE ${{ github.repository }}"

      # Run `asv run` ?
      - name: Run asv benchmarks from root
        run: echo "${{ github.actor }}"

      # Run `asv publish` ?
      - name: Generate html files from results
        run: |
          echo Generate html files
          echo from benchmark results

  # # publish results to static site
  # publish:
  #   needs: [benchmark]
  #   runs-on: self-hosted
  #   steps: checkout gh-pages > checkout results from the branch PR > push gh-pages
